apiVersion: v1
kind: Pod
metadata:
  name: debug-auth
  namespace: app
spec:
  serviceAccountName: auth-service-sa
  containers:
  - name: mc
    image: minio/mc
    command: ["sh","-c","sleep 3600"]
