apiVersion: v1
kind: Pod
metadata:
  name: debug-data
  namespace: app
spec:
  serviceAccountName: data-service-sa
  containers:
  - name: mc
    image: minio/mc
    envFrom:
    - secretRef:
        name: minio-creds
    command: ["sh", "-c", "sleep 3600"]
