apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: app-restrict
  namespace: app
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: gateway
