apiVersion: v1
kind: Pod
metadata:
  name: debug-data
  namespace: app
spec:
  serviceAccountName: data-service-sa
  containers:
  - name: curl
    image: curlimages/curl:8.5.0
    command: ["sleep", "3600"]
