apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: minio-access-binding
  namespace: app
subjects:
- kind: ServiceAccount
  name: data-service-sa
  namespace: app
roleRef:
  kind: Role
  name: minio-access
  apiGroup: rbac.authorization.k8s.io
